<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="1" failures="0" name="ConfigTest.TestPrefix-20150930142920" tests="1" time="0.019">
	<properties/>
	<system-out>
<![CDATA[]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
	<testcase classname="ConfigTest.TestPrefix" name="test_split_prefix_for_sensors" time="0.019">
		<error message="global name 'datapath' is not defined" type="NameError">
<![CDATA[Traceback (most recent call last):
  File "/home/saikappa/workspace/SciPass/python/t/ConfigTest.py", line 55, in test_split_prefix_for_sensors
    datapath.id = 1
NameError: global name 'datapath' is not defined
]]>		</error>
	</testcase>
</testsuite>
