<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="1" failures="0" name="ConfigTest.TestPrefix-20151001171356" tests="5" time="0.161">
	<properties/>
	<system-out>
<![CDATA[]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
	<testcase classname="ConfigTest.TestPrefix" name="test_add_prefix" time="0.029"/>
	<testcase classname="ConfigTest.TestPrefix" name="test_initial_config" time="0.025"/>
	<testcase classname="ConfigTest.TestPrefix" name="test_move_prefix" time="0.042"/>
	<testcase classname="ConfigTest.TestPrefix" name="test_sensor_prefix_split" time="0.035"/>
	<testcase classname="ConfigTest.TestPrefix" name="test_del_prefix" time="0.031">
		<error message="global name 'IPv4Network' is not defined" type="NameError">
<![CDATA[Traceback (most recent call last):
  File "/home/saikappa/workspace/SciPass/python/t/ConfigTest.py", line 92, in test_del_prefix
    self.api.getBalancer("%016x" % self.datapath.id, "R&E").delGroupPrefix("group1",IPv4Network("10.0.20.0/24"))
NameError: global name 'IPv4Network' is not defined
]]>		</error>
	</testcase>
</testsuite>
