<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="0" failures="1" name="BalancerOnlyTest.BalancerInitTest-20151021141736" tests="1" time="51.836">
	<properties/>
	<system-out>
<![CDATA[]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
	<testcase classname="BalancerOnlyTest.BalancerInitTest" name="testBalance" time="51.836">
		<failure message="1120 != 560" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "/home/saikappa/workspace/SciPass/python/t/BalancerOnlyTest.py", line 288, in testBalance
    self.assertEquals(len(flows), 560)
AssertionError: 1120 != 560
]]>		</failure>
	</testcase>
</testsuite>
