<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="0" failures="1" name="ConfigTest.TestPrefix-20150930150721" tests="1" time="0.021">
	<properties/>
	<system-out>
<![CDATA[]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
	<testcase classname="ConfigTest.TestPrefix" name="test_initial_config" time="0.021">
		<failure message="" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "/home/saikappa/workspace/SciPass/python/t/ConfigTest.py", line 28, in test_initial_config
    assert(os.path.isfile(self.file) == 0)
AssertionError
]]>		</failure>
	</testcase>
</testsuite>
