<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="2" failures="0" name="ConfigTest.TestPrefix-20151007154838" tests="5" time="0.149">
	<properties/>
	<system-out>
<![CDATA[]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
	<testcase classname="ConfigTest.TestPrefix" name="test_add_prefix" time="0.028"/>
	<testcase classname="ConfigTest.TestPrefix" name="test_del_prefix" time="0.029"/>
	<testcase classname="ConfigTest.TestPrefix" name="test_move_prefix" time="0.038"/>
	<testcase classname="ConfigTest.TestPrefix" name="test_initial_config" time="0.021">
		<error message="'groups'" type="KeyError">
<![CDATA[Traceback (most recent call last):
  File "/home/saikappa/workspace/SciPass/python/t/ConfigTest.py", line 41, in test_initial_config
    groups = data["switch"]["%016x" % self.datapath.id]["domain"]["R&E"]["groups"]["mode"]["SciDMZ"].keys()
KeyError: 'groups'
]]>		</error>
	</testcase>
	<testcase classname="ConfigTest.TestPrefix" name="test_sensor_prefix_split" time="0.033">
		<error message="'groups'" type="KeyError">
<![CDATA[Traceback (most recent call last):
  File "/home/saikappa/workspace/SciPass/python/t/ConfigTest.py", line 57, in test_sensor_prefix_split
    prefixes = data["switch"]["%016x" % self.datapath.id]["domain"]["R&E"]["groups"]["mode"]["SciDMZ"]["group1"]["prefixes"]
KeyError: 'groups'
]]>		</error>
	</testcase>
</testsuite>
