<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="1" failures="0" name="SimpleBalancerTest.TestStateChange-20151207150255" tests="1" time="2.488">
	<properties/>
	<system-out>
<![CDATA[]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
	<testcase classname="SimpleBalancerTest.TestStateChange" name="test_initial_config" time="2.488">
		<error message="[Errno 2] No such file or directory: '0000000000000001IUPUI.json'" type="IOError">
<![CDATA[Traceback (most recent call last):
  File "/home/saikappa/workspace/SciPass/python/t/SimpleBalancerTest.py", line 553, in test_initial_config
    with open(self.state) as data_file:
IOError: [Errno 2] No such file or directory: '0000000000000001IUPUI.json'
]]>		</error>
	</testcase>
</testsuite>
