<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="1" failures="0" name="ConfigTest.TestPrefix-20150930171706" tests="1" time="0.023">
	<properties/>
	<system-out>
<![CDATA[]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
	<testcase classname="ConfigTest.TestPrefix" name="test_initial_config" time="0.023">
		<error message="'sensor'" type="KeyError">
<![CDATA[Traceback (most recent call last):
  File "/home/saikappa/workspace/SciPass/python/t/ConfigTest.py", line 41, in test_initial_config
    sensors = data["switch"]["%016x" % self.datapath.id]["domain"]["R&E"]["groups"]["sensor"]
KeyError: 'sensor'
]]>		</error>
	</testcase>
</testsuite>
