<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="1" failures="1" name="SimpleBalancerTest.TestPrefix-20151020210502" tests="10" time="0.013">
	<properties/>
	<system-out>
<![CDATA[]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
	<testcase classname="SimpleBalancerTest.TestPrefix" name="test_add_sensor_prefix" time="0.000"/>
	<testcase classname="SimpleBalancerTest.TestPrefix" name="test_get_largest_prefix" time="0.000"/>
	<testcase classname="SimpleBalancerTest.TestPrefix" name="test_get_prefix_sensor" time="0.000"/>
	<testcase classname="SimpleBalancerTest.TestPrefix" name="test_set_prefix_bw" time="0.000"/>
	<testcase classname="SimpleBalancerTest.TestPrefix" name="test_split_prefix" time="0.001"/>
	<testcase classname="SimpleBalancerTest.TestPrefix" name="test_split_prefix_for_sensors" time="0.001"/>
	<testcase classname="SimpleBalancerTest.TestPrefix" name="test_split_prefix_for_sensors_large" time="0.009"/>
	<testcase classname="SimpleBalancerTest.TestPrefix" name="test_split_sensor_prefix" time="0.001"/>
	<testcase classname="SimpleBalancerTest.TestPrefix" name="test_move_sensor_prefix" time="0.000">
		<failure message="" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "/home/saikappa/workspace/SciPass/python/t/SimpleBalancerTest.py", line 227, in test_move_sensor_prefix
    self.assertTrue(res == 1)
AssertionError
]]>		</failure>
	</testcase>
	<testcase classname="SimpleBalancerTest.TestPrefix" name="test_del_sensor_prefix" time="0.001">
		<error message="cannot concatenate 'str' and 'int' objects" type="TypeError">
<![CDATA[Traceback (most recent call last):
  File "/home/saikappa/workspace/SciPass/python/t/SimpleBalancerTest.py", line 192, in test_del_sensor_prefix
    logging.error("REsult:" + res)
TypeError: cannot concatenate 'str' and 'int' objects
]]>		</error>
	</testcase>
</testsuite>
