<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="1" failures="0" name="SimpleBalancerTest.TestStateChange-20151207145843" tests="1" time="0.002">
	<properties/>
	<system-out>
<![CDATA[]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
	<testcase classname="SimpleBalancerTest.TestStateChange" name="test_initial_config" time="0.002">
		<error message="1" type="SystemExit">
<![CDATA[Traceback (most recent call last):
  File "/home/saikappa/workspace/SciPass/python/t/SimpleBalancerTest.py", line 541, in setUp
    readState = False)
  File "./SciPass.py", line 65, in __init__
    self._validateConfig(self.configFile, self.schemaFile)
  File "./SciPass.py", line 502, in _validateConfig
    sys.exit(1)
SystemExit: 1
]]>		</error>
	</testcase>
</testsuite>
